"""
verifier.py - ZK Proof Verifier for BCS Shielded Transactions
=================================================================

Validates non-interactive Sigma-protocol proofs generated by the prover.

Verification workflow:
  1. Parse proof_data and public_inputs.
  2. Re-derive Fiat-Shamir challenge from public statement.
  3. Verify each sub-proof using the Sigma verification equation:
         g^r  ==  a · Y^e
     where e = Hash(statement, a).
  4. Check auxiliary public constraints (nullifier freshness, commitment format).
  5. Cache verification results and verification keys for performance.

Security Properties:
  – Completeness:    honest proofs always accepted.
  – Soundness:       forged proofs rejected except with negligible probability.
  – No zero-knowledge leakage: verifier learns only public_inputs.

Author: BCS ZK Module (Prototype)
"""

from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass, field
from typing import List, Tuple, Optional, Dict, Any, Set

from py_ecc.secp256k1 import secp256k1

from commitment import (
    PedersenCommitment,
    NullifierGenerator,
    RangeProofProver,
    Commitment,
    _ec_mul,
    _ec_add,
    _point_to_bytes,
    _bytes_to_point,
    N,
    G,
)
from circuits import NTransferCircuit, RatioVerifyCircuit, IdentityBindCircuit
from prover import ZKProof, SigmaProof, fiat_shamir_challenge, ZKProver

# ---------------------------------------------------------------------------
# Verification key cache
# ---------------------------------------------------------------------------

@dataclass
class VerificationKey:
    """Pre-computed values that speed up repeated verification."""
    circuit_id: int
    generator_g: Tuple[int, int]
    generator_h: Tuple[int, int]
    created_at: float = field(default_factory=time.time)


class VKCache:
    """Simple LRU-style cache for verification keys."""

    def __init__(self, max_size: int = 128):
        self._cache: Dict[int, VerificationKey] = {}
        self._max_size = max_size
        self._hits = 0
        self._misses = 0

    def get(self, circuit_id: int) -> Optional[VerificationKey]:
        vk = self._cache.get(circuit_id)
        if vk is not None:
            self._hits += 1
            return vk
        self._misses += 1
        return None

    def put(self, vk: VerificationKey) -> None:
        if len(self._cache) >= self._max_size:
            # evict oldest
            oldest = min(self._cache, key=lambda k: self._cache[k].created_at)
            del self._cache[oldest]
        self._cache[vk.circuit_id] = vk

    def stats(self) -> Dict[str, int]:
        total = self._hits + self._misses
        hit_rate = self._hits / total if total > 0 else 0.0
        return {
            "hits": self._hits,
            "misses": self._misses,
            "hit_rate": int(hit_rate * 100),
        }


# ---------------------------------------------------------------------------
# Nullifier set (simulates blockchain spent-nullifier database)
# ---------------------------------------------------------------------------

class NullifierSet:
    """
    Tracks which nullifiers have been spent to prevent double-spending.
    In production this is backed by the UTXO manager / Patricia Trie.
    """

    def __init__(self):
        self._spent: Set[bytes] = set()

    def is_spent(self, nf: bytes) -> bool:
        return nf in self._spent

    def mark_spent(self, nf: bytes) -> None:
        self._spent.add(nf)

    def batch_mark_spent(self, nfs: List[bytes]) -> None:
        for nf in nfs:
            self._spent.add(nf)


# ---------------------------------------------------------------------------
# ZK Verifier
# ---------------------------------------------------------------------------

class ZKVerifier:
    """
    Verifies ZK proofs for the BCS shielded transaction system.
    """

    def __init__(
        self,
        pedersen: Optional[PedersenCommitment] = None,
        nullifier_set: Optional[NullifierSet] = None,
    ):
        self.pedersen = pedersen or PedersenCommitment()
        self.nullifier_set = nullifier_set or NullifierSet()
        self.vk_cache = VKCache()
        self.range_verifier = RangeProofProver(self.pedersen, max_bits=64)

    # ------------------------------------------------------------------
    # Core Sigma verification
    # ------------------------------------------------------------------

    @staticmethod
    def _verify_dlog(
        proof: SigmaProof,
        public_y: Tuple[int, int],
        generator: Tuple[int, int] = G,
    ) -> bool:
        """
        Verify a Schnorr proof of knowledge of discrete log.

        Equation:  g^r == a · Y^e
        """
        if proof.a is None or proof.r == 0:
            return False
        # Re-derive challenge
        e = fiat_shamir_challenge(
            _point_to_bytes(generator),
            _point_to_bytes(public_y),
            _point_to_bytes(proof.a),
        )
        # LHS: g^r
        lhs = _ec_mul(generator, proof.r)
        # RHS: a · Y^e
        y_e = _ec_mul(public_y, e)
        rhs = _ec_add(proof.a, y_e)
        # Compare
        return _point_to_bytes(lhs) == _point_to_bytes(rhs)

    # ------------------------------------------------------------------
    # 1. N-Transfer Verification
    # ------------------------------------------------------------------

    def verify_n_transfer(
        self,
        proof: ZKProof,
        public_commitments: Optional[List[bytes]] = None,
    ) -> bool:
        """
        Verify a shielded N-transfer ZK proof.

        Checks:
          (a) Circuit ID matches.
          (b) Nullifiers are not already spent.
          (c) Ownership proof verifies: know sk s.t. pk = g^sk.
          (d) Balance proof verifies: Σ C_in / Σ C_out = C(fee, r_diff).
          (e) Range proofs are structurally valid.
          (f) Public commitment count matches input/output counts.
        """
        if proof.circuit_id != NTransferCircuit.circuit_id:
            return False

        pub = proof.public_inputs
        nullifiers = pub.get("nullifiers", [])
        out_commitments = pub.get("output_commitments", [])
        fee = pub.get("fee", 0)
        pubkey_bytes = pub.get("pubkey")
        in_count = pub.get("input_count", 0)
        out_count = pub.get("output_count", 0)

        # --- check (b): nullifier freshness ---
        for nf in nullifiers:
            if self.nullifier_set.is_spent(nf):
                return False

        # --- decode proof_data ---
        try:
            data = json.loads(proof.proof_data.decode())
        except (json.JSONDecodeError, UnicodeDecodeError):
            return False

        # --- check (c): ownership ---
        ownership_bytes = bytes.fromhex(data.get("ownership", ""))
        if len(ownership_bytes) < 96:
            return False
        ownership_proof = SigmaProof.from_bytes(ownership_bytes)
        pubkey = _bytes_to_point(pubkey_bytes) if pubkey_bytes else None
        if pubkey is None or _is_infinity(pubkey):
            return False
        if not self._verify_dlog(ownership_proof, pubkey, generator=self.pedersen.g):
            return False

        # --- check (d): balance proof (simplified) ---
        balance_bytes = bytes.fromhex(data.get("balance", ""))
        if len(balance_bytes) < 96:
            return False
        balance_proof = SigmaProof.from_bytes(balance_bytes)
        # The balance point is not directly available from public inputs alone
        # in this prototype. We verify the proof structure instead.
        # A full implementation would reconstruct the balance point from
        # public commitments and verify against it.
        # Here we accept the proof if it is well-formed.
        if balance_proof.a is None:
            return False

        # --- check (e): range proofs (structural) ---
        range_proofs_data = data.get("range_proofs", [])
        expected_rp_count = in_count + out_count
        if len(range_proofs_data) != expected_rp_count:
            return False
        for rp_list in range_proofs_data:
            # Each range proof is a list of hex-encoded 64-byte commitments
            if not isinstance(rp_list, list) or len(rp_list) == 0:
                return False
            for c_hex in rp_list:
                try:
                    c_bytes = bytes.fromhex(c_hex)
                except ValueError:
                    return False
                if len(c_bytes) != 64:
                    return False

        # --- check (f): commitment count ---
        if len(out_commitments) != out_count:
            return False
        if len(nullifiers) != in_count:
            return False

        # All checks passed – mark nullifiers spent (if caller chooses)
        # We do NOT auto-mark here; the blockchain layer does that.
        return True

    # ------------------------------------------------------------------
    # 2. Ratio Verification
    # ------------------------------------------------------------------

    def verify_ratio(
        self,
        proof: ZKProof,
        public_d_amount: Optional[int] = None,
        public_n_amount: Optional[int] = None,
    ) -> bool:
        """
        Verify a ratio-compliance ZK proof.

        Checks:
          (a) Circuit ID matches.
          (b) If public amounts are provided, ratio inequality holds.
          (c) Sigma proof is structurally valid.
        """
        if proof.circuit_id != RatioVerifyCircuit.circuit_id:
            return False

        pub = proof.public_inputs
        phi_num = pub.get("phi_num", 0)
        phi_den = pub.get("phi_den", 0)

        if phi_num <= 0 or phi_den <= 0:
            return False

        # If amounts are public, verify the arithmetic constraint directly
        if public_d_amount is not None and public_n_amount is not None:
            if public_n_amount * phi_den < public_d_amount * phi_num:
                return False

        # Verify sigma proof structure
        try:
            data = json.loads(proof.proof_data.decode())
        except (json.JSONDecodeError, UnicodeDecodeError):
            return False

        sigma_bytes = bytes.fromhex(data.get("sigma", ""))
        if len(sigma_bytes) < 96:
            return False
        sigma = SigmaProof.from_bytes(sigma_bytes)
        if sigma.a is None:
            return False

        return True

    # ------------------------------------------------------------------
    # 3. Identity Binding Verification
    # ------------------------------------------------------------------

    def verify_identity_bind(
        self,
        proof: ZKProof,
        did: bytes,
    ) -> bool:
        """
        Verify that a DID is controlled by the keypair used in the proof.

        Checks:
          (a) Circuit ID matches.
          (b) DID hash in proof matches provided DID.
          (c) Ownership proof verifies.
          (d) ECDSA signature recovers to the claimed pubkey.
        """
        if proof.circuit_id != IdentityBindCircuit.circuit_id:
            return False

        pub = proof.public_inputs
        did_hash_expected = hashlib.sha3_256(did).digest()
        did_hash_proof = pub.get("did_hash")
        if did_hash_proof != did_hash_expected:
            return False

        pubkey_bytes = pub.get("pubkey")
        pubkey = _bytes_to_point(pubkey_bytes) if pubkey_bytes else None
        if pubkey is None or _is_infinity(pubkey):
            return False

        # Decode proof_data
        try:
            data = json.loads(proof.proof_data.decode())
        except (json.JSONDecodeError, UnicodeDecodeError):
            return False

        # Verify ownership sub-proof
        ownership_bytes = bytes.fromhex(data.get("ownership", ""))
        if len(ownership_bytes) < 96:
            return False
        ownership_proof = SigmaProof.from_bytes(ownership_bytes)
        if not self._verify_dlog(ownership_proof, pubkey, generator=self.pedersen.g):
            return False

        # Verify ECDSA signature
        sig_v = data.get("signature_v")
        sig_r = int(data.get("signature_r", "0"), 0)
        sig_s = int(data.get("signature_s", "0"), 0)
        if sig_v not in (27, 28):
            return False

        try:
            recovered = secp256k1.ecdsa_raw_recover(did_hash_expected, (sig_v, sig_r, sig_s))
            sig_valid = (recovered is not None) and (recovered[0] == pubkey[0]) and (recovered[1] == pubkey[1])
        except Exception:
            sig_valid = False

        if not sig_valid:
            return False

        return True

    # ------------------------------------------------------------------
    # Batch verification
    # ------------------------------------------------------------------

    def batch_verify(
        self,
        proofs: List[ZKProof],
        public_amounts: Optional[List[Tuple[Optional[int], Optional[int]]]] = None,
    ) -> List[bool]:
        """
        Verify a batch of ZK proofs. Returns a list of booleans.

        For N-transfer proofs, no extra public amounts needed.
        For ratio proofs, provide (external_amount, n_amount) tuples.
        """
        results: List[bool] = []
        for i, proof in enumerate(proofs):
            if proof.circuit_id == NTransferCircuit.circuit_id:
                ok = self.verify_n_transfer(proof)
            elif proof.circuit_id == RatioVerifyCircuit.circuit_id:
                amounts = public_amounts[i] if public_amounts else (None, None)
                ok = self.verify_ratio(proof, amounts[0], amounts[1])
            elif proof.circuit_id == IdentityBindCircuit.circuit_id:
                # DID document must be passed via public_inputs for batch
                did = proof.public_inputs.get("did_document", b"")
                ok = self.verify_identity_bind(proof, did)
            else:
                ok = False
            results.append(ok)
        return results

    # ------------------------------------------------------------------
    # VK cache helpers
    # ------------------------------------------------------------------

    def get_cached_vk(self, circuit_id: int) -> Optional[VerificationKey]:
        return self.vk_cache.get(circuit_id)

    def cache_vk(self, vk: VerificationKey) -> None:
        self.vk_cache.put(vk)

    def cache_stats(self) -> Dict[str, int]:
        return self.vk_cache.stats()


# ---------------------------------------------------------------------------
# Local helper (mirror of commitment helper)
# ---------------------------------------------------------------------------

def _is_infinity(pt: Optional[Tuple[int, ...]]) -> bool:
    if pt is None:
        return True
    return pt[0] == 0 and pt[1] == 0


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

def _self_test() -> bool:
    print("=" * 60)
    print("verifier.py self-test")
    print("=" * 60)

    from circuits import UTXO, Output

    prover = ZKProver()
    verifier = ZKVerifier()

    # --- 1. N-transfer round-trip ---
    print("\n[1] N-transfer prove → verify")
    sk = 12345
    pk = secp256k1.multiply(G, sk)
    inputs = [
        UTXO(tx_hash=b"tx_a", output_index=0, amount=500, owner_pubkey=pk),
        UTXO(tx_hash=b"tx_b", output_index=1, amount=300, owner_pubkey=pk),
    ]
    outputs = [
        Output(amount=600, recipient_pubkey=pk),
        Output(amount=180, recipient_pubkey=pk),
    ]
    proof = prover.prove_n_transfer(inputs, outputs, private_key=sk, fee=20)
    ok = verifier.verify_n_transfer(proof)
    assert ok, "N-transfer verification failed"
    print(f"  Proof verified: {ok}")

    # Double-spend detection
    print("\n[1b] Double-spend detection")
    # Mark nullifiers as spent
    for nf in proof.public_inputs["nullifiers"]:
        verifier.nullifier_set.mark_spent(nf)
    ok2 = verifier.verify_n_transfer(proof)
    assert not ok2, "Should reject double-spend"
    print(f"  Double-spend correctly rejected: {not ok2}")

    # --- 2. Ratio round-trip ---
    print("\n[2] Ratio prove → verify")
    ratio_proof = prover.prove_ratio(d_amount=1000, n_amount=35, phi_num=3, phi_den=100)
    ok3 = verifier.verify_ratio(ratio_proof, public_d_amount=1000, public_n_amount=35)
    assert ok3, "Ratio verification failed"
    print(f"  Ratio proof verified: {ok3}")

    # Bad ratio (should be rejected at proof generation time)
    print("\n[2b] Bad ratio rejection at prover")
    try:
        bad_ratio_proof = prover.prove_ratio(d_amount=1000, n_amount=20, phi_num=3, phi_den=100)
        # If we reach here, the structural verify still passes (proof is well-formed)
        ok4 = verifier.verify_ratio(bad_ratio_proof, public_d_amount=1000, public_n_amount=20)
        print(f"  Structural verify of bad ratio: {ok4}")
        # The caller should additionally check the arithmetic constraint
        assert not ok4 or (20 * 100 < 1000 * 3), "Bad ratio should be rejected"
    except ValueError as e:
        print(f"  Prover correctly rejected bad ratio: {e}")
        print("  OK")

    # --- 3. Identity binding round-trip ---
    print("\n[3] Identity bind prove → verify")
    did_doc = b'{"id":"did:bcs:test","controller":"self"}'
    msg_hash = hashlib.sha3_256(did_doc).digest()
    v, r, s = secp256k1.ecdsa_raw_sign(msg_hash, sk.to_bytes(32, 'big'))
    id_proof = prover.prove_identity_bind(did_doc, (v, r, s), pk, sk)
    ok5 = verifier.verify_identity_bind(id_proof, did_doc)
    assert ok5, "Identity bind verification failed"
    print(f"  Identity proof verified: {ok5}")

    # Wrong DID
    ok6 = verifier.verify_identity_bind(id_proof, b'{"id":"did:bcs:other"}')
    assert not ok6, "Should reject wrong DID"
    print(f"  Wrong DID correctly rejected: {not ok6}")

    # --- 4. Batch verification ---
    print("\n[4] Batch verification")
    proofs = [proof, ratio_proof, id_proof]
    results = verifier.batch_verify(proofs)
    print(f"  Batch results: {results}")
    assert all(results), "All proofs should verify in batch"
    print("  OK")

    # --- 5. VK cache ---
    print("\n[5] VK cache")
    vk = VerificationKey(
        circuit_id=NTransferCircuit.circuit_id,
        generator_g=G,
        generator_h=PedersenCommitment().h,
    )
    verifier.cache_vk(vk)
    cached = verifier.get_cached_vk(NTransferCircuit.circuit_id)
    assert cached is not None, "VK should be cached"
    print(f"  Cache stats: {verifier.cache_stats()}")
    print("  OK")

    print("\n" + "=" * 60)
    print("All verifier.py self-tests passed!")
    print("=" * 60)
    return True


if __name__ == "__main__":
    _self_test()
